name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: laravel_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d laravel_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # Set up PHP
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    # Check out the code
    - uses: actions/checkout@v4

    # Move to the backend directory
    - name: Navigate to Backend Directory
      working-directory: ./backend
      run: echo "Switched to backend directory"

    # Copy .env file
    - name: Copy .env
      working-directory: ./backend
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Install PHP dependencies
    - name: Install Dependencies
      working-directory: ./backend
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Generate application key
    - name: Generate Key
      working-directory: ./backend
      run: php artisan key:generate

    # Set permissions
    - name: Directory Permissions
      working-directory: ./backend
      run: chmod -R 777 storage bootstrap/cache

    # Configure the database
    - name: Configure Database
      working-directory: ./backend
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: laravel_test
        DB_USERNAME: postgres
        DB_PASSWORD: password
      run: |
        php artisan migrate --force

    # Run Laravel tests
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      working-directory: ./backend
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: laravel_test
        DB_USERNAME: postgres
        DB_PASSWORD: password
      run: php artisan test
